In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd

In [55]:
df = pd.read_csv('./dataset/mobile_price/train.csv')

In [56]:
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [57]:
df.columns.values

array(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'], dtype=object)

In [58]:
len(df.columns.values)

21

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [60]:
continuous_var = []
binary_var = []
for col in df.columns.values:
    if df[col].value_counts().count() > 2 :
        continuous_var.append(col)
    else :
        binary_var.append(col)

target_var = 'price_range'
continuous_var.remove('price_range')
print(len(continuous_var), continuous_var)
print(len(binary_var), binary_var)

14 ['battery_power', 'clock_speed', 'fc', 'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height', 'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time']
6 ['blue', 'dual_sim', 'four_g', 'three_g', 'touch_screen', 'wifi']


In [61]:
from sklearn.naive_bayes import GaussianNB, BernoulliNB

gnb = GaussianNB()
bnb = BernoulliNB()

In [63]:
X = df.drop(target_var, axis=1)
y = df[target_var]

In [85]:
y.value_counts()

price_range
1    500
2    500
3    500
0    500
Name: count, dtype: int64

In [64]:
X.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2   2         20       756  2549     9     7         19   
1        136        3   6        905      1988  2631    17     3          7   
2        145        5   6       1263      1716  2603    11     2          9   
3        131        6   9       1216      1786  2769    16     8         11   
4        141        2  14       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  
0        0             0     1  
1        1             1     0  
2        1             1     0  
3        1             0     0  
4        1             1     0

In [65]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [66]:
X_train.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
582            1232     0          2.9         1   1       1          24   
159            1840     0          0.5         1  12       0          34   
1827           1692     0          2.1         0   4       1           2   
318             508     0          0.8         0   7       1          42   
708             977     1          2.8         1   2       0          35   

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
582     0.3        169        5  17        361       809  1257    16    10   
159     0.7        142        1  16        311      1545  1078     8     0   
1827    0.9        106        1  17       1899      1904  3779     9     3   
318     0.3         94        1   8         39       557   663    13    12   
708     0.6        165        2  15       1502      1862  3714    19     3   

      talk_time  three_g  touch_screen  wifi  
582          16        1             0     0  
159          10        0             0     0  
1827          7        1             1     1  
318           7        1             0     0  
708          10        0             1     1

In [67]:
X_train_continuous = X_train[continuous_var]
X_train_binary = X_train[binary_var]

In [68]:
X_train_continuous.columns, X_train_binary.columns

(Index(['battery_power', 'clock_speed', 'fc', 'int_memory', 'm_dep',
        'mobile_wt', 'n_cores', 'pc', 'px_height', 'px_width', 'ram', 'sc_h',
        'sc_w', 'talk_time'],
       dtype='object'),
 Index(['blue', 'dual_sim', 'four_g', 'three_g', 'touch_screen', 'wifi'], dtype='object'))

In [37]:
gmodel = gnb.fit(X_train_continuous, y_train)
bmodel = bnb.fit(X_train_binary, y_train)

In [69]:
X_test_continuous = X_test[continuous_var]
X_test_binary = X_test[binary_var]

In [70]:
g_log_likelihood = gmodel._joint_log_likelihood(X_test_continuous)
b_log_likelihood = bmodel._joint_log_likelihood(X_test_binary)

In [71]:
g_log_likelihood.shape, b_log_likelihood.shape

((400, 4), (400, 4))

In [72]:
log_likelihood = g_log_likelihood + b_log_likelihood
log_likelihood.shape

(400, 4)

In [73]:
y_classes = y_train.unique()

In [74]:
y_classes = np.sort(y_classes)

In [80]:
g_y_pred = y_classes[np.argmax(g_log_likelihood, axis=1)]
b_y_pred = y_classes[np.argmax(b_log_likelihood, axis=1)]
mix_y_pred = y_classes[np.argmax(log_likelihood, axis=1)]

In [82]:
print(f'GAUSSIAN ACC : {int((g_y_pred==y_test).sum()/len(y_test)*100)} %')
print(f'BERNOULLI ACC : {int((b_y_pred==y_test).sum()/len(y_test)*100)} %')
print(f'MIX ACC : {int((mix_y_pred==y_test).sum()/len(y_test)*100)} %')

GAUSSIAN ACC : 83 %
BERNOULLI ACC : 26 %
MIX ACC : 83 %


In [83]:
y_train.unique()

array([0, 1, 3, 2])

In [84]:
y_train.count()

np.int64(1600)

In [89]:
y_unique = y.unique()
y_unique = np.sort(y_unique)
y_unique, y_unique.shape[0]

(array([0, 1, 2, 3]), 4)

In [101]:
confusion_matrix = np.zeros((y_unique.shape[0], y_unique.shape[0]))
for ans in y_unique:
    for i in y_unique:
        
        confusion_matrix[ans][i] = (mix_y_pred==i).sum()
        print(f'ans : {ans}, i : {i}, c_m[{ans}][{i}] = {confusion_matrix[ans][i]}')

ans : 0, i : 0, c_m[0][0] = 93.0
ans : 0, i : 1, c_m[0][1] = 91.0
ans : 0, i : 2, c_m[0][2] = 98.0
ans : 0, i : 3, c_m[0][3] = 118.0
ans : 1, i : 0, c_m[1][0] = 93.0
ans : 1, i : 1, c_m[1][1] = 91.0
ans : 1, i : 2, c_m[1][2] = 98.0
ans : 1, i : 3, c_m[1][3] = 118.0
ans : 2, i : 0, c_m[2][0] = 93.0
ans : 2, i : 1, c_m[2][1] = 91.0
ans : 2, i : 2, c_m[2][2] = 98.0
ans : 2, i : 3, c_m[2][3] = 118.0
ans : 3, i : 0, c_m[3][0] = 93.0
ans : 3, i : 1, c_m[3][1] = 91.0
ans : 3, i : 2, c_m[3][2] = 98.0
ans : 3, i : 3, c_m[3][3] = 118.0


In [99]:
confusion_matrix[0].sum()

np.float64(400.0)

In [100]:
confusion_matrix

array([[ 93.,  91.,  98., 118.],
       [ 93.,  91.,  98., 118.],
       [ 93.,  91.,  98., 118.],
       [ 93.,  91.,  98., 118.]])

In [102]:
confusion_matrix_bnb = np.zeros((y_unique.shape[0], y_unique.shape[0]))
for ans in y_unique:
    for i in y_unique:
        confusion_matrix_bnb[ans][i] = (b_y_pred==i).sum()

In [109]:
confusion_matrix

array([[ 93.,  91.,  98., 118.],
       [ 93.,  91.,  98., 118.],
       [ 93.,  91.,  98., 118.],
       [ 93.,  91.,  98., 118.]])

In [111]:
# recall
recall = np.zeros(y_unique.shape[0])

for ans in y_unique:
    recall[ans] = confusion_matrix[ans][ans]/confusion_matrix[ans, :].sum()

recall

array([0.2325, 0.2275, 0.245 , 0.295 ])

In [114]:
# precision
precision = np.zeros(y_unique.shape[0])

for ans in y_unique:
    print(f'{confusion_matrix[ans][ans]}', end=', ')
    print(f'{confusion_matrix[:,ans].sum()}')
    precision[ans] = confusion_matrix[ans][ans]/confusion_matrix[:,ans].sum()

precision

93.0, 372.0
91.0, 364.0
98.0, 392.0
118.0, 472.0


array([0.25, 0.25, 0.25, 0.25])

In [117]:
recall_ = recall.sum()/recall.shape[0]
precision_ = precision.sum()/precision.shape[0]
recall_, precision_

(np.float64(0.25), np.float64(0.25))